title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: '/' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
sass:
    sass_dir: _sass
    style: compressed
defaults:
    - scope:
          path: ''
      values:
          layout: 'default'
    - scope:
          path: 'careers'
          type: 'pages'
      values:
          title: Careers at Informal
          superTitle: Careers
          intro: |
              Our cooperatively owned and governed company is a growing team with world-class
              expertise in distributed systems, formal verification, and open-source
              ecosystem.
    - scope:
          path: ''
          type: 'careers'
      values:
          layout: 'career-details'
plugins:
    - jekyll-feed
collections:
    careers:
        output: true
        sort_by: jobTitle
        permalink: /:collection/:name
