careerCategories:
    - All # Uhh, don't change this one
    - Engineering
    - Development
    - Design
    - Marketing
footerMenuItems:
    - label: About Us
      url: /about
    - label: Products & Services
      url: /products-and-services
    - label: News & Publications
      url: /news-and-publications
    - label: Team
      url: /team
    - label: Blog
      url: /blog
    - label: Careers
      url: /careers
menuItems:
    - label: Home
      url: /
    - label: Products
      url: /products
    - label: Services
      url: /services
      subMenuItems:
          - label: Auditing
            url: /services/auditing
          - label: Interchange Operations
            url: /services/interchange-operations
    - label: Cooperative
      url: /cooperative
    - label: Careers
      url: /careers
    - label: Community
      url: /community
socialLinks:
    - label: Facebook
      icon: fab fa-facebook
      url: http://facebook.com/
    - label: Instagram
      icon: fab fa-instagram
      url: http://instagram.com/
    - label: Twitter
      icon: fab fa-twitter
      url: http://twitter.com/
    - label: Facebook
      icon: fab fa-linkedin
      url: http://linkedin.com/
teamMembers:
  - name: Marie Leaf
    bio: |
      Marie works on product development to support local money and mutual
  - name: Shon Feder
    bio: |
      Marie works on product development to support local money and mutual
  - name: Josef Widder
    bio: |
      Marie works on product development to support local money and mutual
  - name: Marie Leaf
    bio: |
      Marie works on product development to support local money and mutual
  - name: Marie Leaf
    bio: |
      Marie works on product development to support local money and mutual
  - name: Joshua Jeffrey
    bio: |
      Marie works on product development to support local money and mutual
tweets:
  - 1436208066882686980
  - 1436675105405480961
  - 1436722378051104768
  - 1436208066882686980
  - 1436675105405480961
  - 1436722378051104768
values:
  - label: Play
    description: Approach the world with open curiosity
  - label: Think
    description: Research, experiment, measure, validate
  - label: Dance
    description: Balance planning and improvisation
  - label: Love
    description: Psychological safety first
  - label: Serve
    description: Help others help you, recursively
  - label: Own
    description: Responsibility is for the taking
  - label: Challenge
    description: Push boundaries, raise the bar
