careerCategories:
    - All # Uhh, don't change this one
    - Engineering
    - Development
    - Design
    - Marketing
footerMenuItems:
    - label: About Us
      url: /about
    - label: Products
      url: /products
    - label: Auditing
      url: /services/auditing
    - label: Proof of Stake Validator
      url: /services/proof-of-stake-validator
    - label: Careers
      url: /careers
menuItems:
    - label: Home
      url: /
    - label: About Us
      url: /about
    - label: Products
      url: /products
    - label: Services
      url: /services
      subMenuItems:
          - label: Auditing
            url: /services/auditing
          - label: Proof of Stake Validator
            url: /services/proof-of-stake-validator
    - label: Careers
      url: /careers
socialLinks:
    - label: Facebook
      icon: fab fa-facebook
      url: http://facebook.com/
    - label: Instagram
      icon: fab fa-instagram
      url: http://instagram.com/
    - label: Twitter
      icon: fab fa-twitter
      url: http://twitter.com/
    - label: Facebook
      icon: fab fa-linkedin
      url: http://linkedin.com/
teamMembers:
  - name: Marie Leaf
    bio: |
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus, odit
      quisquam. Quisquam aspernatur, hic, culpa voluptatum ducimus voluptas
      placeat amet quo iure dignissimos delectus dicta, asperiores quibusdam nam
      totam repellendus.
  - name: Shon Feder
    bio: |
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque, nemo? At
      est, culpa asperiores excepturi quibusdam iusto, eveniet quas molestias
      velit alias quis assumenda incidunt, voluptates ab voluptatibus eum?
      Aliquam!
  - name: Josef Widder
    bio: |
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus tempore
      dolor voluptate quis magnam eveniet a veniam distinctio laudantium
      asperiores illo, voluptatem rem exercitationem hic similique, consequatur,
      quasi omnis deserunt?
  - name: Marie Leaf
    bio: |
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi labore totam
      laudantium ad amet repellat quisquam omnis sed, necessitatibus ipsum laborum
      reiciendis repudiandae odio, porro placeat obcaecati a esse ratione.
  - name: Marie Leaf
    bio: |
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas inventore
      ea eligendi incidunt maxime, nisi praesentium quo, id, pariatur vitae quod.
      Quisquam obcaecati non pariatur voluptatum itaque vel, ullam officiis.
  - name: Joshua Jeffrey
    bio: |
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus sit, nisi
      repudiandae impedit earum dolor neque culpa at est vitae deserunt officia
      voluptatem beatae libero labore qui ipsam! Cupiditate, deleniti.
      twee
ts:
  - 1436208066882686980
  - 1436675105405480961
  - 1436857655306371081
  - 1436208066882686980
  - 1436675105405480961
  - 1436857655306371081
values:
  - label: Play
    description: Approach the world with open curiosity
  - label: Think
    description: Research, experiment, measure, validate
  - label: Dance
    description: Balance planning and improvisation
  - label: Love
    description: Psychological safety first
  - label: Serve
    description: Help others help you, recursively
  - label: Own
    description: Responsibility is for the taking
  - label: Challenge
    description: Push boundaries, raise the bar
