careerCategories:
    - All # Uhh, don't change this one
    - Engineering
    - Development
    - Design
    - Marketing
footerMenuItems:
    - label: About Us
      url: /about
    - label: Products & Services
      url: /products-and-services
    - label: News & Publications
      url: /news-and-publications
    - label: Team
      url: /team
    - label: Blog
      url: /blog
    - label: Careers
      url: /careers
menuItems:
    - label: Home
      url: /
    - label: Products
      url: /products
    - label: Services
      url: /services
      subMenuItems:
          - label: Auditing
            url: /services/auditing
          - label: Validation
            url: /services/validation
    - label: Cooperative
      url: /cooperative
    - label: Careers
      url: /careers
    - label: Community
      url: /community
socialLinks:
    - label: Facebook
      icon: fab fa-facebook
      url: http://facebook.com/
    - label: Instagram
      icon: fab fa-instagram
      url: http://instagram.com/
    - label: Twitter
      icon: fab fa-twitter
      url: http://twitter.com/
    - label: Facebook
      icon: fab fa-linkedin
      url: http://linkedin.com/
