blockChainProducts:
    - title: tendermint-rs
      color: teal
      icon: assets/img/product-logos/tendermint-rs.svg
      socialLinks:
        - label: Github
          icon: fab fa-github
          url: https://github.com/informalsystems/tendermint-rs
      description: |
          Tendermint is a Byzantine Fault Tolerant state machine replication engine for applications written in Rust.
    - title: ibc-rs
      color: purple
      icon: assets/img/product-logos/ibc-rs.svg
      socialLinks:
        - label: Github
          icon: fab fa-github
          url: https://github.com/informalsystems/ibc-rs
      description: |
          Inter-Blockchain Communication (IBC) is a protocol for secure,
          packet-based communication between distinct blockchains.
    - title: Hermes
      color: yellow
      icon: assets/img/product-logos/hermes.svg
      socialLinks:
        - label: Website
          icon: far fa-globe-americas
          url: https://hermes.informal.systems/relayer.html
      description: |
          Hermes is an open-source Rust implementation of a relayer for IBC, released under the ibc-relayer-cli crate.
verificationProducts:
  - title: Apalache
    color: teal
    icon: assets/img/product-logos/apalache.svg
    socialLinks:
      - label: Github
        icon: fab fa-github
        url: https://github.com/informalsystems/apalache
      - label: Website
        icon: far fa-globe-americas
        url: https://apalache.informal.systems/
    description: |
        Symbolic model checker for TLA+ – formally verify TLA+ specifications for real-world distributed systems protocols
  - title: Model Based Testing
    color: yellow
    icon: assets/img/product-logos/model-based-testing.svg
    socialLinks:
      - label: Website
        icon: far fa-globe-americas
        url: https://aaronmw.github.io/informal-systems-2/services/auditing/
    description: |
       A methodology and tool used to auto-generate tests for real implementations from an underlying TLA+ model.
